# Generated by Django 5.1.7 on 2025-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FincaRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('propietario', models.CharField(max_length=255)),
                ('fotografias', models.ImageField(blank=True, null=True, upload_to='static/img/fincas/')),
            ],
            options={
                'db_table': 'finca_record',
            },
        ),
    ]
