# Generated by Django 5.1.7 on 2025-04-17 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FincaRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fotografias', models.ImageField(blank=True, null=True, upload_to='static/img/fincas/')),
                ('tiene_parqueadero', models.BooleanField(default=False)),
                ('tiene_restaurante', models.BooleanField(default=False)),
                ('experiencias', models.TextField(blank=True, help_text='Describe brevemente las experiencias ofrecidas', null=True)),
                ('costo_experiencia', models.CharField(blank=True, help_text='Ejemplo: $30.000 por persona o Ingreso gratuito', max_length=255, null=True)),
                ('biografia_propietario', models.TextField(blank=True, help_text='Una breve reseña del propietario', null=True)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Finca',
                'verbose_name_plural': 'Registros Fincas',
                'db_table': 'finca_record',
            },
        ),
    ]
