# Generated by Django 5.1.7 on 2025-04-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('actividad', models.TextField(help_text='Describe qué se hace en esta experiencia.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img/experiencias/')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_finca', to='fincas.fincarecordmodel')),
            ],
        ),
    ]
