# Generated by Django 5.1.7 on 2025-03-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fincarecordmodel',
            options={'verbose_name': 'Registro Finca', 'verbose_name_plural': 'Registros Fincas'},
        ),
    ]
