# Generated by Django 5.1.7 on 2025-04-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0002_experienciamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fincarecordmodel',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción general de la finca', null=True),
        ),
    ]
