# Generated by Django 5.1.7 on 2025-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0004_evaluacionfinca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionfinca',
            name='biodiversidad',
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='asistencia_tecnica',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='cercas_vivas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='cobertura_forestal',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='conservacion_fuentes',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='control_plagas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='fertilizacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='participacion_comunitaria',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='recoleccion_agua_lluvia',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
    ]
