# Generated by Django 5.1.7 on 2025-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0005_remove_evaluacionfinca_biodiversidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionfinca',
            name='asociacion_cultivos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='educacion_caficultor',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='formalizacion_laboral',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='gestion_residuos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='preservacion_bosque',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='rotacion_cultivos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='sistemas_riego',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='tratamiento_aguas_residuales',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='uso_insumos_ecologicos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='uso_plantas_nativas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='uso_tecnologia',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionfinca',
            name='variedades_cafe',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
    ]
