# Generated by Django 5.1.7 on 2025-05-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0008_comentariofinca_delete_evaluacionusuariofinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariofinca',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
